name: 'laba 6'

on:
  push:
    branches:
      - main

env:
  Version_Project: "0.0.1"
  Version_Release: "0.0.1"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps (optional)
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev  # если нужно

      - name: Configure CMake
        run: cmake -B build . -DPATCH_VERSION="${{ env.Version_Project }}"

      - name: Build
        run: cmake --build build

      - name: Run Program (optional test)
        run: ./build/laba4

      - name: Make pkg
        run: cmake --build build --target package

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: build/laba4-${{ env.Version_Project }}-Linux.deb

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B build . -DPATCH_VERSION="${{ env.Version_Project }}"

      - name: Build project
        run: cmake --build build --config Release

      - name: Create zip
        run: |
          Compress-Archive -Path ./build/Release/laba4.exe -DestinationPath containers-${{ env.Version_Project }}.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: containers-${{ env.Version_Project }}.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.Version_Release }}
          name: Release ${{ env.Version_Release }}
          draft: false
          prerelease: false
          files: |
            artifacts/linux-package/laba4-${{ env.Version_Project }}-Linux.deb
            artifacts/windows-package/containers-${{ env.Version_Project }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}